name: Build Group Tool App

on:
  push:
    branches: [ main ]
    paths:
      - 'group_tool/**'   # Only trigger if files in group_tool/ change
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # adjust if needed

    - name: Install dependencies
      working-directory: group_tool
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      working-directory: group_tool
      run: |
        pyinstaller --onefile --windowed main.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: workflow-launcher-exe
        path: group_tool/dist/WorkflowManager.exe
